function area = getTriangleArea(vertices)
    area = 0.5 * abs( vertices{2}(1) * vertices{3}(2) ...
                    - vertices{3}(1) * vertices{2}(2) ...
                    - vertices{1}(1) * vertices{3}(2) ...
                    + vertices{3}(1) * vertices{1}(2) ...
                    + vertices{1}(1) * vertices{2}(2) ...
                    + vertices{2}(1) * vertices{1}(2) ...
                    )
end